import db from "../client.js";

await db.connect();
await seedProducts();
await db.end();
console.log("🌱 Products seeded.");

async function seedProducts() {
  const products = [
    {
      product_name: "",
      product_category: "",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "Cordless Circular Saw",
      product_category: "construction tools",
      product_description: " A cordless battery powered Skill saw",
      basic_price: 385.27,
      product_img: "https://images.pexels.com/photos/30237884/pexels-photo-30237884.jpeg/",
    },
    {
      product_name: "concrete magnesium float",
      product_category: "construction tools",
      product_description: "a long 16' piece of metal meant to detail fresh concrete",
      basic_price: 54.98,
      product_img: "https://www.istockphoto.com/photo/industrial-worker-on-construction-site-laying-sealant-for-waterproofing-cement-gm535411978-94897317?utm_source=pexels&utm_medium=affiliate&utm_campaign=sponsored_photo&utm_content=srp_inline_portrait_media&utm_term=concrete%20tool",
    },
    {
      product_name: "shovel",
      product_category: "construction tools",
      product_description: "Meant to dig ",
      basic_price: 32.98,
      product_img: "https://www.istockphoto.com/photo/shovel-in-heap-of-dirt-gm172146091-255252?utm_source=pexels&utm_medium=affiliate&utm_campaign=sponsored_photo&utm_content=srp_inline_media&utm_term=shovel",
    },
    {
      product_name: "skid steer ",
      product_category: "construction tools",
      product_description: " a front loading piece of equipment",
      basic_price: 44995.00,
      product_img: "https://www.pexels.com/photo/skid-loader-on-a-baseball-field-25559744/",
    },
    {
      product_name: "mini excavator",
      product_category: "construction tools",
      product_description: "a better shovel",
      basic_price: 25000.00,
      product_img: "https://www.pexels.com/photo/mini-excavator-in-melbourne-public-parking-lot-31461653/",
    },
    {
      product_name: "nail gun ",
      product_category: "construction tools",
      product_description: " a air powered nail driver ",
      basic_price: 299.11,
      product_img: "https://www.pexels.com/photo/drilling-hole-on-the-wall-6473980/",
    },
    {
      product_name: "hammer",
      product_category: "construction tools",
      product_description: " a metal hammer ",
      basic_price: 29.94,
      product_img: "https://www.pexels.com/photo/black-claw-hammer-on-brown-wooden-plank-209235/",
    },
    {
      product_name: "",
      product_category: "food",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "food",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "food",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "White Bread",
      product_category: "food",
      product_description: "White Bread is sold by the loaf",
      basic_price: 2.99,
      product_img:
        "https://images.pexels.com/photos/2942327/pexels-photo-2942327.jpeg",
    },
    {
      product_name: "Chicken breast",
      product_category: "food",
      product_description: "Chicken Breast is sold per pound",
      basic_price: 7.99,
      product_img:
        "https://images.pexels.com/photos/5769384/pexels-photo-5769384.jpeg",
    },
    {
      product_name: "Banana",
      product_category: "food",
      product_description: "Banana's price is determined per pound",
      basic_price: 3.99,
      product_img:
        "https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg",
    },
    {
      product_name: "Strawberry",
      product_category: "food",
      product_description: "Strawberry's price is determined per pound",
      basic_price: 4.99,
      product_img:
        "https://images.pexels.com/photos/6944172/pexels-photo-6944172.jpeg",
    },
  ];
  return products;
}