import { createProducts } from "#db/queries/products";

export async function seedProducts() {
  const products = [
    {
      product_name: "",
      product_category: "",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "electronics",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "vehicles",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "medical supply's",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "construction tools",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "construction tools",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "construction tools",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "construction tools",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "construction tools",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "construction tools",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "construction tools",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "food",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "food",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "",
      product_category: "food",
      product_description: "",
      basic_price: 1.11,
      product_img: "",
    },
    {
      product_name: "White Bread",
      product_category: "food",
      product_description: "White Bread is sold by the loaf",
      basic_price: 2.99,
      product_img:
        "https://images.pexels.com/photos/2942327/pexels-photo-2942327.jpeg",
    },
    {
      product_name: "Chicken breast",
      product_category: "food",
      product_description: "Chicken Breast is sold per pound",
      basic_price: 7.99,
      product_img:
        "https://images.pexels.com/photos/5769384/pexels-photo-5769384.jpeg",
    },
    {
      product_name: "Banana",
      product_category: "food",
      product_description: "Banana's price is determined per pound",
      basic_price: 3.99,
      product_img:
        "https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg",
    },
    {
      product_name: "Strawberry",
      product_category: "food",
      product_description: "Strawberry's price is determined per pound",
      basic_price: 4.99,
      product_img:
        "https://images.pexels.com/photos/6944172/pexels-photo-6944172.jpeg",
    },
  ];
  for (const product of products) {
      await createProducts(product);
    }
    console.log("completed seeding products");
}